import Link from "next/link";
import { getAdminAIObservability, getAdminGyms } from "@core/services/dashboard/admin";
import { AdminFrame, getAdminPageContext } from "@/lib/page-context";
import { dashboardFilters, firstParam, type PageSearchParams } from "@/lib/search-params";
import { EmptyState, MetricCard, PageHeader, Pagination, Panel, StatusBadge, formatDateTime } from "@/components/ui";

export const dynamic = "force-dynamic";

export default async function AdminAIPage({ searchParams }: { searchParams: PageSearchParams }) {
  const params = await searchParams;
  const { actorUserId, actor } = await getAdminPageContext();
  const input = { ...dashboardFilters(params), eventType: firstParam(params.eventType), status: firstParam(params.status), gymId: firstParam(params.gymId), dateFrom: firstParam(params.dateFrom), dateTo: firstParam(params.dateTo) };
  const [data, gyms] = await Promise.all([getAdminAIObservability(actorUserId, input), getAdminGyms(actorUserId, { page: 1, pageSize: 50 })]);
  const filters = { eventType: firstParam(params.eventType), status: firstParam(params.status), gymId: firstParam(params.gymId), dateFrom: firstParam(params.dateFrom), dateTo: firstParam(params.dateTo) };
  return <AdminFrame actor={actor}><PageHeader eyebrow="AI operations" title="Observability" description="Concise event telemetry only—no hidden reasoning, credentials or raw private prompts." />
    <div className="metric-grid"><MetricCard label="Total events" value={data.metrics.total} accent /><MetricCard label="Requests today" value={data.metrics.requestsToday} /><MetricCard label="Successes" value={data.metrics.successes} /><MetricCard label="Errors" value={data.metrics.errors} /><MetricCard label="Tool failures" value={data.metrics.toolFailures} /><MetricCard label="Average latency" value={data.metrics.averageLatencyMs ? `${Math.round(data.metrics.averageLatencyMs)} ms` : "—"} /><MetricCard label="Average tool latency" value={data.metrics.averageToolLatencyMs ? `${Math.round(data.metrics.averageToolLatencyMs)} ms` : "—"} /><MetricCard label="Input tokens" value={data.metrics.inputTokens ?? "—"} /><MetricCard label="Output tokens" value={data.metrics.outputTokens ?? "—"} /><MetricCard label="Estimated cost" value={data.metrics.estimatedCostUsd ? `$${data.metrics.estimatedCostUsd}` : "Unavailable"} /></div>
    <form className="filters"><div className="field"><label htmlFor="eventType">Event type</label><input id="eventType" name="eventType" defaultValue={filters.eventType} maxLength={80} /></div><div className="field compact"><label htmlFor="status">Status</label><select id="status" name="status" defaultValue={filters.status ?? ""}><option value="">All</option><option>PROCESSING</option><option>SUCCESS</option><option>ERROR</option></select></div><div className="field compact"><label htmlFor="gymId">Gym</label><select id="gymId" name="gymId" defaultValue={filters.gymId ?? ""}><option value="">All gyms</option>{gyms.items.map((gym) => <option key={gym.id} value={gym.id}>{gym.name}</option>)}</select></div><div className="field compact"><label htmlFor="dateFrom">From</label><input id="dateFrom" name="dateFrom" type="date" defaultValue={filters.dateFrom} /></div><div className="field compact"><label htmlFor="dateTo">To</label><input id="dateTo" name="dateTo" type="date" defaultValue={filters.dateTo} /></div><button className="button" type="submit">Filter</button></form>
    <div className="panel table-wrap">{data.events.items.length ? <table><thead><tr><th>Event</th><th>Status</th><th>Tools</th><th>Model</th><th>User / gym</th><th>Latency</th><th>Time</th></tr></thead><tbody>{data.events.items.map((event) => <tr key={event.id}><td><Link className="text-link" href={`/admin/ai/${event.id}`}>{event.eventType}</Link></td><td><StatusBadge value={event.status} /></td><td>{event.toolExecutions.length ? event.toolExecutions.map((tool) => tool.toolName).join(", ") : "—"}<span className="cell-subtitle">{event.toolExecutions.filter((tool) => tool.status !== "SUCCESS").length ? `${event.toolExecutions.filter((tool) => tool.status !== "SUCCESS").length} failed` : ""}</span></td><td>{event.model ?? "—"}</td><td>{event.user?.firstName ?? event.user?.telegramUsername ?? "—"}<span className="cell-subtitle">{event.gym?.name ?? "Platform"}</span></td><td>{event.latencyMs ? `${event.latencyMs} ms` : "—"}</td><td>{formatDateTime(event.createdAt)}</td></tr>)}</tbody></table> : <EmptyState>No AI events match these filters.</EmptyState>}</div><Pagination page={data.events.page} pageCount={data.events.pageCount} total={data.events.total} href="/admin/ai" params={filters} />
    <div className="split-grid section-gap"><Panel title="Model distribution"><div className="panel-body stack">{data.models.map((model) => <div className="detail-item" key={model.model ?? "unknown"}><span>Model</span><strong>{model.model ?? "Unknown"} · {model._count._all}</strong></div>)}</div></Panel><Panel title="Recent errors"><div className="panel-body stack">{data.recentErrors.length ? data.recentErrors.map((event) => <div className="detail-item" key={event.id}><span>{formatDateTime(event.createdAt)}</span><strong>{event.eventType}</strong><div className="cell-subtitle">{event.errorMessage ?? "No safe error summary."}</div></div>) : <EmptyState>No recent errors.</EmptyState>}</div></Panel></div>
  </AdminFrame>;
}
